---
title: "Nomes de ruas Porto"
author: "Rafael Belokurows"
date: "`r Sys.Date()`"
output: html_document
---

<!-- #https://www.wikidata.org/wiki/Property:P21 -->
<!-- https://github.com/cran/tidywikidatar -->
<!-- https://fmeireles.com/blog/rstats/genderbr-predizer-sexo/ -->
```{r setup, include=FALSE}
library("tidywikidatar")
tw_enable_cache()
tw_set_cache_folder(path = fs::path(fs::path_home_r(), "R", "tw_data"))
tw_set_language(language = "en")
tw_create_cache_folder(ask = FALSE)

livrary(devtools)
devtools::install_github("meirelesff/genderBR")
library(genderBR)
```

## R Markdown


```{r cars}
codigos = read.csv("C:\\Users\\belokurowsr\\OneDrive - Kantar\\Desktop\\Kantar\\Puntos Sondeo\\codigos_postais.csv",fileEncoding = "UTF8")

codigos %>% filter(desig_postal == "PORTO") %>% head(10) %>% View()
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
